
[provider]
address = "0xaabf35dabd9a05100b6d794558ec75be5899c588"
env = "local"
config = "~/.sui/sui_config/client.yaml"

[envs]
devnet = { url = "https://sui-devnet.artifact.systems:443/" }
testnet = { url = "https://fullnode.testnet.sui.io:443/" }
local = { url = "http://127.0.0.1:9000/" }
